<a href="https://colab.research.google.com/github/subham-28/PyTorch/blob/main/dataset_dataloader_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from sklearn.datasets import make_classification
import torch

In [34]:
x,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [35]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [36]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [37]:
x=torch.tensor(x,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [38]:
from torch.utils.data import Dataset, DataLoader

In [39]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [40]:
dataset=CustomDataset(x,y)

In [41]:
len(dataset)

10

In [42]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [44]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [45]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-0.9382, -0.5430],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------

### Pipeline

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [7]:
#scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [9]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
#label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [12]:
#numpy arr to pytorch tensors
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)

y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [13]:
x_train_tensor.shape

torch.Size([455, 30])

In [22]:
# Convert tensors to float32 and adjust shape for y_train_tensor
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float().unsqueeze(1)
x_test_tensor = x_test_tensor.float()
y_test_tensor = y_test_tensor.float().unsqueeze(1)

In [23]:
from torch.utils.data import TensorDataset, DataLoader, Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [24]:
# Create custom datasets
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

In [25]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

building the model

In [26]:
import torch.nn as nn

class MyNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [27]:
learning_rate=0.1
epochs=100

In [28]:
loss_function=nn.BCELoss()

In [29]:
# create model
model=MyNN(x_train_tensor.shape[1])

#define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):

  #forward pass
  y_pred=model(x_train_tensor)

  #loss
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

  #zero gradient
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #update params
  optimizer.step()

  #print loss
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8685867190361023
Epoch: 2, Loss: 0.6464670300483704
Epoch: 3, Loss: 0.518317699432373
Epoch: 4, Loss: 0.4395546317100525
Epoch: 5, Loss: 0.38734254240989685
Epoch: 6, Loss: 0.3504258990287781
Epoch: 7, Loss: 0.3229212164878845
Epoch: 8, Loss: 0.3015478253364563
Epoch: 9, Loss: 0.28436899185180664
Epoch: 10, Loss: 0.2701828181743622
Epoch: 11, Loss: 0.2582097053527832
Epoch: 12, Loss: 0.24792364239692688
Epoch: 13, Loss: 0.23895753920078278
Epoch: 14, Loss: 0.2310471534729004
Epoch: 15, Loss: 0.22399738430976868
Epoch: 16, Loss: 0.21766060590744019
Epoch: 17, Loss: 0.21192289888858795
Epoch: 18, Loss: 0.20669472217559814
Epoch: 19, Loss: 0.2019045203924179
Epoch: 20, Loss: 0.19749437272548676
Epoch: 21, Loss: 0.19341664016246796
Epoch: 22, Loss: 0.18963183462619781
Epoch: 23, Loss: 0.1861068159341812
Epoch: 24, Loss: 0.18281345069408417
Epoch: 25, Loss: 0.17972779273986816
Epoch: 26, Loss: 0.1768292337656021
Epoch: 27, Loss: 0.1740998774766922
Epoch: 28, Loss: 0.17152418196201324
Epoch: 29, Loss: 0.16908851265907288
Epoch: 30, Loss: 0.16678084433078766
Epoch: 31, Loss: 0.164590522646904
Epoch: 32, Loss: 0.16250814497470856
Epoch: 33, Loss: 0.16052529215812683
Epoch: 34, Loss: 0.15863440930843353
Epoch: 35, Loss: 0.15682871639728546
Epoch: 36, Loss: 0.15510211884975433
Epoch: 37, Loss: 0.15344908833503723
Epoch: 38, Loss: 0.1518646478652954
Epoch: 39, Loss: 0.15034420788288116
Epoch: 40, Loss: 0.14888370037078857
Epoch: 41, Loss: 0.14747931063175201
Epoch: 42, Loss: 0.1461276113986969
Epoch: 43, Loss: 0.14482536911964417
Epoch: 44, Loss: 0.1435697376728058
Epoch: 45, Loss: 0.14235803484916687
Epoch: 46, Loss: 0.14118778705596924
Epoch: 47, Loss: 0.14005665481090546
Epoch: 48, Loss: 0.13896259665489197
Epoch: 49, Loss: 0.13790363073349
Epoch: 50, Loss: 0.13687793910503387
Epoch: 51, Loss: 0.13588383793830872
Epoch: 52, Loss: 0.13491976261138916
Epoch: 53, Loss: 0.1339842528104782
Epoch: 54, Loss: 0.13307590782642365
Epoch: 55, Loss: 0.13219347596168518
Epoch: 56, Loss: 0.13133575022220612
Epoch: 57, Loss: 0.1305016130208969
Epoch: 58, Loss: 0.129690021276474
Epoch: 59, Loss: 0.1288999617099762
Epoch: 60, Loss: 0.12813055515289307
Epoch: 61, Loss: 0.1273808777332306
Epoch: 62, Loss: 0.1266501396894455
Epoch: 63, Loss: 0.1259375661611557
Epoch: 64, Loss: 0.12524238228797913
Epoch: 65, Loss: 0.12456394731998444
Epoch: 66, Loss: 0.12390159070491791
Epoch: 67, Loss: 0.12325469404459
Epoch: 68, Loss: 0.12262266129255295
Epoch: 69, Loss: 0.12200494110584259
Epoch: 70, Loss: 0.12140101194381714
Epoch: 71, Loss: 0.12081035226583481
Epoch: 72, Loss: 0.12023254483938217
Epoch: 73, Loss: 0.11966709047555923
Epoch: 74, Loss: 0.11911354213953018
Epoch: 75, Loss: 0.11857154220342636
Epoch: 76, Loss: 0.11804064363241196
Epoch: 77, Loss: 0.1175205409526825
Epoch: 78, Loss: 0.11701081693172455
Epoch: 79, Loss: 0.11651118099689484
Epoch: 80, Loss: 0.11602127552032471
Epoch: 81, Loss: 0.11554080247879028
Epoch: 82, Loss: 0.11506945639848709
Epoch: 83, Loss: 0.11460698395967484
Epoch: 84, Loss: 0.11415309458971024
Epoch: 85, Loss: 0.113707534968853
Epoch: 86, Loss: 0.11327004432678223
Epoch: 87, Loss: 0.11284039169549942
Epoch: 88, Loss: 0.11241835355758667
Epoch: 89, Loss: 0.11200370639562607
Epoch: 90, Loss: 0.11159622669219971
Epoch: 91, Loss: 0.11119573563337326
Epoch: 92, Loss: 0.11080203950405121
Epoch: 93, Loss: 0.11041492223739624
Epoch: 94, Loss: 0.11003421992063522
Epoch: 95, Loss: 0.10965975373983383
Epoch: 96, Loss: 0.10929138213396072
Epoch: 97, Loss: 0.10892891883850098
Epoch: 98, Loss: 0.10857219994068146
Epoch: 99, Loss: 0.10822110623121262
Epoch: 100, Loss: 0.10787548869848251

In [31]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.5479